version: "3"
services:
    strapi:
        container_name: strapi
        # build: .
        image: strapi/strapi
        restart: unless-stopped
        env_file: .env
        environment:
            DATABASE_CLIENT: ${DATABASE_CLIENT}
            DATABASE_HOST: ${DATABASE_HOST}
            DATABASE_PORT: ${DATABASE_PORT}
            DATABASE_NAME: ${DATABASE_NAME}
            DATABASE_USERNAME: ${DATABASE_USERNAME}
            DATABASE_PASSWORD: ${DATABASE_PASSWORD}

        volumes:
            - ./app:/srv/app
        ports:
            - "1337:1337"
        networks:
            - strapi
        # depends_on:
        #     - strapiDB

    # strapiDB:
    #     container_name: strapiDB
    #     platform: linux/amd64 #for platform error on Apple M1 chips
    #     restart: unless-stopped
    #     env_file: .env
    #     image: postgres:12.0-alpine
    #     environment:
    #         POSTGRES_USER: ${DATABASE_USERNAME}
    #         POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    #         POSTGRES_DB: ${DATABASE_NAME}
    #     volumes:
    #         - strapi-data:/var/lib/postgresql/data/ #using a volume
    #         #- ./data:/var/lib/postgresql/data/ # if you want to use a bind folder

    #     ports:
    #         - "5432:5432"
    #     networks:
    #         - strapi

# volumes:
#     strapi-data:

networks:
    strapi:
        name: Strapi
        driver: bridge
