CREATE TABLE category (
    category_id varchar(25) PRIMARY KEY,
    category_name varchar(50),
    category_url varchar(50),
    rank integer,
    back_ground varchar(512),
    icon varchar(512),
    ctime timestamp(3),
    mtime timestamp(3),
    show_type integer,
    item_type integer,
    promote_tag_cap integer,
    promote_priority integer
);
CREATE TABLE tag (
    id integer PRIMARY KEY,
    tag_id varchar(25),
    CONSTRAINT index_id UNIQUE (tag_id),
    tag_name varchar(50),
    color varchar(10),
    icon varchar(512),
    back_ground varchar(100),
    show_navi integer,
    ctime timestamp(3),
    mtime timestamp(3),
    id_type integer,
    tag_alias varchar(50),
    post_article_count integer,
    concern_user_count integer
);

CREATE TABLE "user" (
    user_id varchar(25) PRIMARY KEY,
    user_name varchar(255),
    company varchar(255),
    job_title varchar(255),
    avatar_large varchar(512),
    level integer,
    description text,
    followee_count integer,
    follower_count integer,
    post_article_count integer,
    digg_article_count integer,
    got_digg_count integer,
    got_view_count integer,
    post_shortmsg_count integer,
    digg_shortmsg_count integer,
    isfollowed boolean,
    favorable_author integer,
    power integer,
    study_point integer,
    identity integer,
    is_select_annual boolean,
    select_annual_rank integer,
    annual_list_type integer,
    account_amount integer,
    is_vip boolean,
    become_author_days integer,
    collection_set_article_count integer,
    recommend_article_count_daily integer,
    article_collect_count_daily integer
);

CREATE TABLE article (
    article_id varchar(25) PRIMARY KEY,
    user_id varchar(25),
    category_id varchar(25),
    visible_level integer,
    link_url text,
    cover_image text,
    is_gfw integer,
    title text,
    brief_content text,
    is_english integer,
    is_original integer,
    user_index float,
    original_type integer,
    original_author varchar(50),
    content text,
    ctime timestamp(3),
    mtime timestamp(3),
    rtime timestamp(3),
    draft_id varchar(19),
    view_count integer,
    collect_count integer,
    digg_count integer,
    comment_count integer,
    hot_index integer,
    is_hot integer,
    rank_index float,
    status integer,
    verify_status integer,
    audit_status integer,
    mark_content text,
    display_count integer,
    tag_ids text[],
    is_markdown integer,
    app_html_content text,
    FOREIGN KEY (user_id) REFERENCES "user"(user_id),
    FOREIGN KEY (category_id) REFERENCES category(category_id)
);
